// AUTO-GENERATED by `cargo xtask gen-manifest` - DO NOT EDIT

/** Version of plugin packages (all @arborium/* packages share this version) */
export const pluginVersion = "1.4.0";

/** All available languages */
export const availableLanguages: string[] = [
  "asciidoc",
  "diff",
  "jinja2",
  "markdown",
  "svelte",
  "typst",
  "vue",
];