# Evergarden Fall (dark)
name = "Evergarden Fall"
variant = "dark"

[colors]
bg = "#232a2e"
keyword = "#f57f82"
function = "#cbe3b3"
string = "#dbe6af"
type = "#f5d098"
number = "#f3c0e5"
macro = "#b3e3ca"
