//! Static grammar provider for the arborium crate.
//!
//! This module provides `StaticProvider`, a `GrammarProvider` implementation
//! that creates `TreeSitterGrammar` instances for enabled language features.
//!
//! # Generated Code
//!
//! This file is automatically generated from the grammar registry
//! (`langs/group-*/*/def/arborium.kdl`). Do not edit manually.

use std::collections::HashMap;

use arborium_highlight::{tree_sitter::TreeSitterGrammar, GrammarProvider};

#[allow(unused_imports)]
use arborium_highlight::tree_sitter::TreeSitterGrammarConfig;

/// A provider that creates tree-sitter grammars for enabled languages.
///
/// Grammars are lazily created on first use and cached.
pub struct StaticProvider {
    grammars: HashMap<&'static str, TreeSitterGrammar>,
}

impl Default for StaticProvider {
    fn default() -> Self {
        Self::new()
    }
}

impl StaticProvider {
    /// Create a new static provider.
    pub fn new() -> Self {
        Self {
            grammars: HashMap::new(),
        }
    }

    /// Normalize a language name to its canonical form.
    fn normalize_language(language: &str) -> &'static str {
        match language {
            // Aliases (generated from arborium.kdl)
<% for (alias, canonical) in aliases { %>
            "<%= alias %>" => "<%= canonical %>",
<% } %>
            // Known canonical IDs pass through as-is
            // (leak the string to get &'static str - this is fine since language names are finite)
            _ => Box::leak(language.to_string().into_boxed_str()),
        }
    }

    /// Create a grammar for a language.
    #[allow(unused_variables)]
    fn create_grammar(language: &str) -> Option<TreeSitterGrammar> {
        macro_rules! try_lang {
            ($feature:literal, $module:ident, $primary:literal) => {
                #[cfg(feature = $feature)]
                if language == $primary {
                    let config = TreeSitterGrammarConfig {
                        language: crate::$module::language().into(),
                        highlights_query: &crate::$module::HIGHLIGHTS_QUERY,
                        injections_query: crate::$module::INJECTIONS_QUERY,
                        locals_query: crate::$module::LOCALS_QUERY,
                    };
                    return TreeSitterGrammar::new(config).ok();
                }
            };
        }

        // All languages (generated from arborium.kdl)
<% for (feature, module, grammar_id) in languages { %>
        try_lang!("<%= feature %>", <%= module %>, "<%= grammar_id %>");
<% } %>

        None
    }
}

impl GrammarProvider for StaticProvider {
    type Grammar = TreeSitterGrammar;

    #[cfg(not(target_arch = "wasm32"))]
    async fn get(&mut self, language: &str) -> Option<&mut Self::Grammar> {
        let normalized = Self::normalize_language(language);

        // Create grammar if not cached
        if !self.grammars.contains_key(normalized)
            && let Some(grammar) = Self::create_grammar(normalized)
        {
            self.grammars.insert(normalized, grammar);
        }

        self.grammars.get_mut(normalized)
    }

    #[cfg(target_arch = "wasm32")]
    async fn get(&mut self, language: &str) -> Option<&mut Self::Grammar> {
        let normalized = Self::normalize_language(language);

        // Create grammar if not cached
        if !self.grammars.contains_key(normalized)
            && let Some(grammar) = Self::create_grammar(normalized)
        {
            self.grammars.insert(normalized, grammar);
        }

        self.grammars.get_mut(normalized)
    }
}
